bubble: bubble_sort.cpp
	g++ -std=c++11 -O2 -o bubble_sort.x bubble_sort.cpp

insertion: insertion_sort.cpp
	g++ -std=c++11 -O2 -o insertion_sort.x insertion_sort.cpp

counting: counting_sort.cpp
	g++ -std=c++11 -O2 -o counting_sort.x counting_sort.cpp

selection: selection_sort.cpp
	g++ -std=c++11 -O2 -o selection_sort.x selection_sort.cpp

sort: sort_sort.cpp
	g++ -std=c++11 -O2 -o sort_sort.x sort_sort.cpp

genrand: genRandom.cpp
	g++ -std=c++11 -O2 -o genRandom.x genRandom.cpp
